### ISSUE TITLE
occured erro when catkin_make

### ISSUE THREAD

**Issue by ChangerC77** [UMich-BipedLab/CLF_reactive_planning_system#1]
When I download this file and put these in my workspace, and I've downloaded customized_ grid_ map、planner_ Msgs and inf_ Msgs, but when catkin_make, errors are reported:
1. [ 53%] Building CXX object customized_grid_map/grid_map_filters/CMakeFiles/grid_map_filters.dir/src/MinInRadiusFilter.cpp.o
/home/ros/navigation/src/CLF_reactive_planning_system/src/test_plane_fitting.cpp: In function ‘int main(int, char**)’:
/home/ros/navigation/src/CLF_reactive_planning_system/src/test_plane_fitting.cpp:189:27: error: ‘using element_type = class rviz_visual_tools::RvizVisualTools {aka class rviz_visual_tools::RvizVisualTools}’ has no member named ‘publishABCDPlaneWithCenter’; did you mean ‘publishCylinder’?
            visual_tools_->publishABCDPlaneWithCenter(plane_coefficients[0],
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           publishCylinder

2. [ 60%] Building CXX object customized_grid_map/grid_map_filters/CMakeFiles/grid_map_filters.dir/src/ColorMapFilter.cpp.o
/home/ros/navigation/src/CLF_reactive_planning_system/src/clf_rrt.cpp: In member function ‘bool bipedlab::CLFRRTStarPlanner::runCLFRRTAlgorithm(size_t, double, bool)’:
/home/ros/navigation/src/CLF_reactive_planning_system/src/clf_rrt.cpp:379:71: error: no matching function for call to ‘pcl::PointXYZI::PointXYZI(float, float, double, int)’
                                     (float) it.x, (float) it.y, 0.1, 0));
                                                                       ^
can you tell me how  to solve this? 
computer version: ubuntu18.04, ros-melodic
Thanks!

**Comment by brucejk** [comment]
Hi, 

Thanks for using our packages! 

Please remove [Line 105 to Line 129](https://github.com/UMich-BipedLab/CLF_reactive_planning_system/blob/8232c7567626ebcdd4b43eee73d8aa2f5c8e3963/CMakeLists.txt#L105) in CMakeLists.txt. That need additional [package](https://github.com/PickNikRobotics/rviz_visual_tools). I will remove it in the next release.

**Comment by brucejk** [comment]
Hi, 

Thanks for using our packages! 

1. Please remove [Line 105 to Line 129](https://github.com/UMich-BipedLab/CLF_reactive_planning_system/blob/8232c7567626ebcdd4b43eee73d8aa2f5c8e3963/CMakeLists.txt#L105) in CMakeLists.txt. That needs additional [package](https://github.com/PickNikRobotics/rviz_visual_tools). I will remove it in the next release. 
2. Have you installed the PCL library? If you do and still have this problem, please add a constructor to accept `pcl::PointXYZI::PointXYZI(float, float, double, int)` in your PCL library. 

Please let me know if you encounter other problems.

**Comment by ChangerC77** [comment]
Sorry to bother you, but there are a lot of errors. I'm trying to solve them, but I still encounter many problems I cannot fix by myself, thanks for solution for the first error, I follow your solution and fixed that, but still have more issues and most of these are similar to above, errors are reported:
[ 73%] Building CXX object customized_grid_map/grid_map_rviz_plugin/CMakeFiles/grid_map_rviz_plugin.dir/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp.o
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:66:13: error: ‘boost::rviz’ has not been declared
 void boost::rviz::FrameManager::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
             ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: In function ‘void qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:9: error: ‘FrameManager’ was not declared in this scope
         FrameManager *_t = static_cast<FrameManager *>(_o);
         ^~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:9: note: suggested alternative:
In file included from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:9:0:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/frame_manager.h:64:7: note:   ‘rviz::FrameManager’
 class FrameManager : public QObject
       ^~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:23: error: ‘_t’ was not declared in this scope
         FrameManager *_t = static_cast<FrameManager *>(_o);
                       ^~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:23: note: suggested alternative: ‘_o’
         FrameManager *_t = static_cast<FrameManager *>(_o);
                       ^~
                       _o
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:40: error: ‘FrameManager’ does not name a type
         FrameManager *_t = static_cast<FrameManager *>(_o);
                                        ^~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:53: error: expected ‘>’ before ‘*’ token
         FrameManager *_t = static_cast<FrameManager *>(_o);
                                                     ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:53: error: expected ‘(’ before ‘*’ token
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:54: error: expected primary-expression before ‘>’ token
         FrameManager *_t = static_cast<FrameManager *>(_o);
                                                      ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:69:59: error: expected ‘)’ before ‘;’ token
         FrameManager *_t = static_cast<FrameManager *>(_o);
                                                           ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:78:27: error: ‘FrameManager’ has not been declared
             typedef void (FrameManager::*_t)();
                           ^~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:78:41: error: expected unqualified-id before ‘*’ token
             typedef void (FrameManager::*_t)();
                                         ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:78:41: error: expected ‘)’ before ‘*’ token
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:35: error: ‘_t’ does not name a type; did you mean ‘_o’?
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                   ^~
                                   _o
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:38: error: expected ‘>’ before ‘*’ token
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                      ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:38: error: expected ‘(’ before ‘*’ token
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:39: error: expected primary-expression before ‘>’ token
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                       ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:63: error: ‘_t’ does not name a type; did you mean ‘_o’?
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                                               ^~
                                                               _o
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:68: error: ‘FrameManager’ has not been declared
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                                                    ^~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:79:102: error: expected ‘)’ before ‘{’ token
             if (*reinterpret_cast<_t *>(_a[1]) == static_cast<_t>(&FrameManager::fixedFrameChanged)) {
                                                                                                      ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:83:9: error: expected primary-expression before ‘}’ token
         }
         ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:76:14: warning: unused variable ‘result’ [-Wunused-variable]
         int *result = reinterpret_cast<int *>(_a[0]);
              ^~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: At global scope:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:88:26: error: ‘boost::rviz’ has not been declared
 const QMetaObject boost::rviz::FrameManager::staticMetaObject = {
                          ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:94:27: error: ‘boost::rviz’ has not been declared
 const QMetaObject *boost::rviz::FrameManager::metaObject() const
                           ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:94:60: error: non-member function ‘const QMetaObject* metaObject()’ cannot have cv-qualifier
 const QMetaObject *boost::rviz::FrameManager::metaObject() const
                                                            ^~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: In function ‘const QMetaObject* metaObject()’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:96:21: error: ‘QScopedPointer<QObjectData> QObject::d_ptr’ is protected within this context
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                     ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1:0,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/frame_manager.h:35,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:439:33: note: declared protected here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:96:21: error: invalid use of non-static data member ‘QObject::d_ptr’
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                     ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1:0,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/frame_manager.h:35,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:439:33: note: declared here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:96:50: error: ‘QScopedPointer<QObjectData> QObject::d_ptr’ is protected within this context
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                                                  ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1:0,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/frame_manager.h:35,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:439:33: note: declared protected here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:96:50: error: invalid use of non-static data member ‘QObject::d_ptr’
     return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
                                                  ^~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1:0,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/frame_manager.h:35,
                 from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:9:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:439:33: note: declared here
     QScopedPointer<QObjectData> d_ptr;
                                 ^~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: At global scope:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:99:14: error: ‘boost::rviz’ has not been declared
 void *boost::rviz::FrameManager::qt_metacast(const char *_clname)
              ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: In function ‘void* qt_metacast(const char*)’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:103:35: error: invalid use of ‘this’ in non-member function
         return static_cast<void*>(this);
                                   ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:104:40: error: cannot call member function ‘virtual void* QObject::qt_metacast(const char*)’ without object
     return QObject::qt_metacast(_clname);
                                        ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: At global scope:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:107:12: error: ‘boost::rviz’ has not been declared
 int boost::rviz::FrameManager::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
            ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: In function ‘int qt_metacall(QMetaObject::Call, int, void**)’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:109:43: error: cannot call member function ‘virtual int QObject::qt_metacall(QMetaObject::Call, int, void**)’ without object
     _id = QObject::qt_metacall(_c, _id, _a);
                                           ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:114:32: error: invalid use of ‘this’ in non-member function
             qt_static_metacall(this, _c, _id, _a);
                                ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: At global scope:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:125:13: error: ‘boost::rviz’ has not been declared
 void boost::rviz::FrameManager::fixedFrameChanged()
             ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp: In function ‘void fixedFrameChanged()’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_frame_manager.cpp:127:27: error: invalid use of ‘this’ in non-member function
     QMetaObject::activate(this, &staticMetaObject, 0, nullptr);
                           ^~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:66:13: error: ‘boost::grid_map_rviz_plugin’ has not been declared
 void boost::grid_map_rviz_plugin::_RosTopicDisplay::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
             ^~~~~~~~~~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp: In function ‘void qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:9: error: ‘_RosTopicDisplay’ was not declared in this scope
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
         ^~~~~~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:9: note: suggested alternative:
In file included from /home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:9:0:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/../../../../../../src/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/message_filter_display.h:47:7: note:   ‘grid_map_rviz_plugin::_RosTopicDisplay’
 class _RosTopicDisplay : public rviz::Display {
       ^~~~~~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:27: error: ‘_t’ was not declared in this scope
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                           ^~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:27: note: suggested alternative: ‘_o’
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                           ^~
                           _o
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:44: error: ‘_RosTopicDisplay’ does not name a type
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                                            ^~~~~~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:61: error: expected ‘>’ before ‘*’ token
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                                                             ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:61: error: expected ‘(’ before ‘*’ token
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:62: error: expected primary-expression before ‘>’ token
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                                                              ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:69:67: error: expected ‘)’ before ‘;’ token
         _RosTopicDisplay *_t = static_cast<_RosTopicDisplay *>(_o);
                                                                   ^
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp: At global scope:
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:79:26: error: ‘boost::grid_map_rviz_plugin’ has not been declared
 const QMetaObject boost::grid_map_rviz_plugin::_RosTopicDisplay::staticMetaObject = {
                          ^~~~~~~~~~~~~~~~~~~~
/home/ros/navigation/build/customized_grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/moc_message_filter_display.cpp:85:27: error: ‘boost::grid_map_rviz_plugin’ has not been declared
 const QMetaObject *boost::grid_map_rviz_plugin::_RosTopicDisplay::metaObject() const
                           ^~~~~~~~~~~~~~~~~~~~

about PCL, I have downloaded it and tested it can be used. I need to study how to solve it
thanks for replying!

**Comment by brucejk** [comment]
Hi, 

Have you follow the instruction in [grid_map](https://github.com/UMich-BipedLab/customized_grid_map)?
If so, are you able to run some simple unit tests?

**Comment by ZWT006** [comment]
I install grid_map by `sudo apt-get install ros-$ROS_DISTRO-grid-map`, just fix the first problem, and build succeed. In Ubuntu20.04

**Comment by brucejk** [comment]
Thanks for reporting back. Since it is resolved, I will close this issue. Feel free to reopen it if encounter similar issues.
